version: '3'
services:
  pay-tcp-proxy:
    build: .
    ports:
      - 443:443
    environment:
      - SERVER_DNS=nginx-backend
    depends_on:
      - nginx-backend
  nginx-backend:
    image: nginx:1-alpine
    ports:
      - 443
    volumes:
      - nginx-backend-ssl:/etc/ssl/self-signed-certs/
      - ./local-testing-config/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./local-testing-config/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

volumes:
  nginx-backend-ssl:
    driver: local
