version: '3'
services:
  nginx-frontend:
    image: nginx:1-alpine
    ports:
      - 443:443
    environment:
      - PAY_TCP_PROXY=pay-tcp-proxy
      - PROXY_PROTOCOL=on
    volumes:
      - nginx-backend-ssl:/etc/ssl/self-signed-certs/
      - ./local-testing-config/nginx-frontend.conf:/etc/nginx/nginx.conf.default
      - ./local-testing-config/entrypoint-frontend.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    depends_on:
      - pay-tcp-proxy
  pay-tcp-proxy:
    build: .
    ports:
      - 443
    environment:
      - SERVER_DNS=nginx-backend
      - PROXY_PROTOCOL=on
    depends_on:
      - nginx-backend
  nginx-backend:
    image: nginx:1-alpine
    ports:
      - 443
    volumes:
      - nginx-backend-ssl:/etc/ssl/self-signed-certs/
      - ./local-testing-config/nginx-backend.conf:/etc/nginx/conf.d/default.conf
      - ./local-testing-config/entrypoint-backend.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

volumes:
  nginx-backend-ssl:
    driver: local
